# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adc02af705773e06276915757f162b1bc9984241b3a14b60e0da127ad3fd81c40d639bce8f647128f5a5f1cc84932b4968c5200b3b4081f37926c59592c1ebab

test:
  secret_key_base: 745956a47d57386a8c15a041234fb98d6bad61ffb93bd33a48280722c860de35651c3eb8ed9849ce590b1ee73bca22f9836c9917696171e1a1b2dbd6817014e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
